HOSTS:
  ubuntu-16-04:
    roles:
      - master
    platform: ubuntu-16.04-x64
    image: registry.binaryvoid.com/binaryvoid/beaker-base:latest
    hypervisor: docker
    docker_cmd: '["/sbin/init", "/usr/sbin/sshd -D"]'
CONFIG:
  type: foss
